### ISSUE TITLE
How about it's performance on KITTI 3D ?

### ISSUE THREAD

**Issue by cuge1995** [zaiweizhang/H3DNet#7]

**Comment by zaiweizhang** [comment]
Hi,

Thanks for your interest in our work!
We have not tried to train or test on KITTI 3D mainly due to that the codebase we are using, VoteNet, does not work well with outdoor Lidar pointcloud. 
See issue here: https://github.com/facebookresearch/votenet/issues/53

We think that applying our idea to 3D lidar pointcloud detection should be beneficial and we are also working on related follow up research projects. Stay tuned!
